name: "Push test"
on: push

concurrency:
  group: ${{ github.event.number || github.run_id }}
  cancel-in-progress: true

jobs:
  unit-test-with-asan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ matrix.arch }}
      - name: "checkout"
        uses: actions/checkout@v3

      - name: "install dependencies"
        run: sudo ./misc/install-deps.sh -y

      - name: "configure build env"
        run: |
          uanme -a
          ./configure

      - name: "build the source"
        run: make ASAN=1

      - name: "run unit tests"
        run: make unittest ASAN=1 TESTARG="-v"

  pre-commit-check:
    runs-on: ubuntu-latest
    steps:
      - name: "check out uftrace source"
        uses: actions/checkout@v3

      - name: "install dependencies"
        uses: actions/setup-python@v3

      - name: "run pre-commit"
        uses: pre-commit/action@v3.0.0
